
---
- name: Working with ansible handlers
  hosts: redhat
  ignore_errors: true
  ignore_unreachable: true
  become: true
  become_user: root
  become_method: su
  remote_user: root
  tasks:
      - name: Getting all fact from the hosts
        debug:
           var: ansible_facts
