
---
- name: finding file on the remote nodes
  ignore_errors: true
  remote_user: root
  become: true
  become_user: root
  become_method: su
  hosts: redhat 
  tasks:
     - name: finding a file 'learning_vim'
       find:
          path: /home/reuben/leahh
          size: -1m
          recurse: true 



