---
- name: Learning flushing handlers 
  remote_user: root
  become_user: root
  ignore_unreachable: true
  become_method: su
  ignore_errors: true
  hosts: redhat
  become: true
  tasks: 
    - name: Starting 'mariadb' service
      service:
          name: mariadb
          state: started
      notify: "mariadb started or stopped"

    - name: Ensures all handler that have been notified to be executed  
      meta: flush_handlers

    - name: Stopping 'mariadb' service
      service:
          name: mariadb
          state: stopped
      notify: "mariadb started or stopped"
  handlers: 
    - name: The debug handler
      debug:
         msg: "The message  should be printed twice"
      listen: "mariadb started or stopped"
